### ISSUE TITLE
Private Repository Support

### ISSUE THREAD

**Issue by NerdsvilleCEO** [treeder/dj#6]
Issue moved from https://github.com/treeder/go/issues/10

**Comment by treeder** [comment]
It should, uses your local settings for the most part. Give it a try. 

For Go, the focus should be on local vendoring (glide is great).

**Comment by NerdsvilleCEO** [comment]
Yup seems to work, thanks! :+1:  Is there much of a difference between govendor and glide? I used govendor

**Comment by treeder** [comment]
Doubt it, i'm sure they're pretty similar, whichever you like best. :)

**Comment by NerdsvilleCEO** [comment]
Woot! thanks for all the help :)
